version: '3.7'

services:
  nginx:
    build:
      context: ./docker
      dockerfile: Dockerfile-nginx
    volumes:
      - ./:/var/www/optymyze_assessment:cached
    ports:
      - 10302:80
    networks:
      - optymyze
  fpm:
    build:
      context: ./docker
      dockerfile: Dockerfile-php
    volumes:
      - ./:/var/www/optymyze_assessment/:cached
    networks:
      - optymyze
  db:
    container_name: "database"
    image: mariadb:10.2.29
    ports:
      - "3317:3306"
    environment:
      - MYSQL_DATABASE=optymyze-assessment
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - persistent:/var/lib/mysql
      - ./docker/build/db:/docker-entrypoint-initdb.d/
volumes:
  persistent:
networks:
  optymyze:
